<?php


namespace Modular\traits;


use Illuminate\Support\Str;
use Modular\traits\Structure\App;
use Modular\traits\Structure\Config;
use Modular\traits\Structure\Database;
use Modular\traits\Structure\PublicFolder;
use Modular\traits\Structure\Resource;
use Modular\traits\Structure\Route;

trait Structure
{
    use App, Resource, Route, Database, Config, PublicFolder;
    /**
     * @var
     */
    private $packagePath;

    /**
     * set package's path
     * @param $path
     */
    function setPackagePath($path)
    {
        $this->packagePath = $path;
    }

    /**
     * get the name of package
     *
     * @param $plural , this flag indicates if you want plural name or not
     * @return mixed
     */
    function getPackageName($plural = false)
    {
        $name = ucfirst($this->sanitize($this->getConsole()->argument('name')));
        if ($plural)
            return strtolower($this->str_plural($name));
        return $name;
    }

    /**
     * package's full path
     *
     * @return string
     */
    function getPackagePath()
    {
        return $this->packagePath;
    }

    /**
     * create the package
     */
    function initPackageFolder()
    {
        $this->createFolders($this->getPackagePath(), $this->getPackageName());
        $this->initAppFolder();
        $this->initDatabasesFolder();
        $this->initResourcesFolder();
        $this->initRoutesFolder();
        $this->initConfigFolder();
        $this->initPublicFolder();

    }

    /**
     * generate all package classes with their
     * folders
     */
    function initPackageClasses()
    {
        array_map(function ($class) {
            $method = "generate$class";
            $this->{$method}();
        }, $this->__classesAutoGenerated());
    }

    private function __classesAutoGenerated()
    {
        return ['Model', 'Resource', 'Controller', 'Repository', 'Request', 'Migration'];
    }
}